### ISSUE TITLE
Code seems to be working, but...

### ISSUE THREAD

**Issue by akaAMAZING** [delusionx/PoESniper#2]
Here is my current view:

http://prntscr.com/po7ft6

Was config.json incorrectly set up or?

**Comment by infernumx** [comment]
This tool is for bulk exchange at the moment, your search identifier is for normal item sales.
If you go into your browser and paste that identifier to the end of /trade/exchange/Blight/ you'll see the same results because it's not the correct identifier for bulk exchange.
I'm working on a new branch at the moment to implement live searches for normal trades as well, but it's not done yet.

**Comment by akaAMAZING** [comment]
Oh okay, gotcha. Yes it is working as intended for Bulk Exchange.

Is there a way to automatically capture the listing onto clipboard ready for pasting into chat?

**Comment by infernumx** [comment]
I just use PoE Trades Companion for that: https://github.com/lemasato/POE-Trades-Companion
Select the whisper message, ctrl+c and it will auto paste it into PoE.

**Comment by akaAMAZING** [comment]
Awesome - shall look into it.

Great program from what I see. Keep up the good work!

**Comment by infernumx** [comment]
Make sure you redownload the entire source because I just made some big fixes and changes, especially to the config which I can see you're missing from your screenshot. Enjoy!
